[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -D RF_DATA_PIN=27
  -D RF_INVERT_INPUT=0
  -D RF_INPUT_PULLUP=0
